name: schema_builder
description: A builder for generating Genkit schema extension types.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: '>=3.0.0 <5.0.0'
  source_gen: '>=3.1.0 <5.0.0'
  code_builder: ^4.10.0
  dart_style: ^3.0.0
  analyzer: '>=7.4.0 <9.0.0'
  genkit:
    path: ../../
  json_schema_builder: ^0.1.3

dev_dependencies:
  lints: ^3.0.0
