name: genkit_anthropic
description: Anthropic plugin for Genkit Dart.
resolution: workspace
version: 0.0.1-dev.3
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: ^3.10.0

dependencies:
  anthropic_sdk_dart: ^0.3.1
  genkit: ^0.10.0-dev.12
  meta: ^1.17.0
  schemantic: ^0.0.1-dev.14

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
