name: schema_generator
description: A generator that creates Dart classes from a JSON schema.
publish_to: 'none'
environment:
  sdk: ^3.10.0

dependencies:
  build: ^4.0.0
  code_builder: ^4.10.0
  dart_style: ^3.1.2
  http: ^1.2.1
  json_annotation: ^4.9.0
  source_gen: ^4.0.1
