name: genkit_shelf
description: Shelf integration for Genkit Dart.
resolution: workspace
version: 0.0.1-dev.9
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.9
  schemantic: ^0.0.1-dev.11
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  http: ^1.6.0
  test: ^1.29.0
