name: genkit_shelf
description: Shelf integration for Genkit Dart.
resolution: workspace
version: 0.0.1-dev.1
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  genkit: any
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
