name: genkit_firebase_ai
description: Firebase AI plugin for Genkit Dart.
version: 0.0.1-dev.1
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.1
  schemantic: ^0.0.1-dev.1
  firebase_ai: ^3.6.1
  firebase_core: ^4.3.0
  meta: ^1.16.0
  logging: ^1.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.8.0
  flutter_test:
    sdk: flutter

# Used to resolve local packages during development
dependency_overrides:
  genkit:
    path: ../genkit
  schemantic:
    path: ../schemantic
