name: genkit_firebase_ai
description: Firebase AI plugin for Genkit Dart.
version: 0.0.1-dev.2
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: ^3.10.0

dependencies:
  firebase_app_check: ^0.4.1
  firebase_ai: ^3.8.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  genkit: ^0.10.0-dev.14
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.17.0
  schemantic: ^0.0.1-dev.16

dev_dependencies:
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter

# Used to resolve local packages during development
dependency_overrides:
  genkit:
    path: ../genkit
  schemantic:
    path: ../schemantic
