name: schemantic
description: A general-purpose builder for generating type-safe data classes and JSON schemas from abstract definitions.
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0
resolution: workspace
version: 0.0.1-dev.16
environment:
  sdk: ^3.10.0

dependencies:
  analyzer: ^10.0.0
  build: ^4.0.4
  code_builder: ^4.10.0
  dart_style: ^3.1.4
  json_schema_builder: ^0.1.3
  source_gen: ^4.2.0

dev_dependencies:
  build_test: ^3.5.5
  logging: ^1.3.0
  test: ^1.29.0
