name: schemantic
description: A general-purpose builder for generating type-safe data classes and JSON schemas from abstract definitions.
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0
resolution: workspace
version: 0.0.1-dev.3
environment:
  sdk: ^3.10.0

dependencies:
  build: ^4.0.4
  source_gen: ^4.1.2
  code_builder: ^4.10.0
  dart_style: ^3.1.4
  analyzer: ^10.0.0
  json_schema_builder: ^0.1.3

dev_dependencies:
  lints: ^6.0.0
  build_test: ^3.5.5
  test: ^1.29.0
