name: genkit_chrome_sample
description: A sample app to test genkit_chrome in the browser.
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.10
  genkit_chrome:
    path: ../../packages/genkit_chrome
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.10.5
  build_web_compilers: ^4.4.7
