name: ai_features
description: A starting point for Genkit Dart test applications.
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  genkit: ^0.10.0-dev.17
  genkit_google_genai: ^0.0.1-dev.17
  logging: ^1.3.0
  schemantic: ^0.0.1-dev.18

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
