name: ai_features
description: A starting point for Genkit Dart test applications.
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  genkit: any
  genkit_google_genai: any
  logging: ^1.3.0
  schemantic: any

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
