name: ai_features
description: A starting point for Genkit Dart test applications.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  genkit: any
  genkit_google_genai: any
  schemantic: any
  args: ^2.4.2
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.10.5
  lints: ^5.0.0
  test: ^1.24.0
