name: openai_compat_sample
publish_to: none
description: Genkit Dart OpenAI compatibility test application
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.10
  genkit_openai_compat: ^0.0.1-dev.1
  schemantic: ^0.0.1-dev.12

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
