name: firebase_ai_testapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_ai: any
  firebase_core: any
  cupertino_icons: ^1.0.8
  genkit:
    path: ../../packages/genkit
  genkit_firebase_ai:
    path: ../../packages/genkit_firebase_ai
  genkit_schema_builder:
    path: ../../packages/genkit_schema_builder

dev_dependencies:
  build_runner: ^2.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  genkit:
    path: ../../packages/genkit
  genkit_firebase_ai:
    path: ../../packages/genkit_firebase_ai
  genkit_schema_builder:
    path: ../../packages/genkit_schema_builder
