name: firebase_ai_testapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

flutter:
  uses-material-design: true

dependencies:
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_ai: ^3.6.1
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  genkit:
    path: ../../packages/genkit
  genkit_firebase_ai:
    path: ../../packages/genkit_firebase_ai
  logging: ^1.3.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  record: ^6.1.2
  schemantic:
    path: ../../packages/schemantic

dev_dependencies:
  build_runner: ^2.10.5
  dart_flutter_team_lints: ^3.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  genkit:
    path: ../../packages/genkit
  genkit_firebase_ai:
    path: ../../packages/genkit_firebase_ai
  schemantic:
    path: ../../packages/schemantic
