name: firebase_ai_testapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  firebase_ai: ^3.6.1
  firebase_core: ^4.3.0
  record: ^6.1.2
  audioplayers: ^6.0.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  logging: ^1.3.0
  genkit:
    path: ../../packages/genkit
  genkit_firebase_ai:
    path: ../../packages/genkit_firebase_ai
  genkit_schema_builder:
    path: ../../packages/genkit_schema_builder

dev_dependencies:
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


dependency_overrides:
  genkit:
    path: ../../packages/genkit
  genkit_firebase_ai:
    path: ../../packages/genkit_firebase_ai
  genkit_schema_builder:
    path: ../../packages/genkit_schema_builder
