name: firebase_ai_testapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  firebase_ai: any
  firebase_core: any
  record: ^5.1.0
  audioplayers: ^6.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  logging: ^1.3.0
  genkit:
    path: ../../packages/genkit
  genkit_firebase_ai:
    path: ../../packages/genkit_firebase_ai
  genkit_schema_builder:
    path: ../../packages/genkit_schema_builder

dev_dependencies:
  build_runner: ^2.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


dependency_overrides:
  genkit:
    path: ../../packages/genkit
  genkit_firebase_ai:
    path: ../../packages/genkit_firebase_ai
  genkit_schema_builder:
    path: ../../packages/genkit_schema_builder
