name: middleware_example
description: A simple example of middleware in Genkit.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  genkit: any
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
