name: genkit_openai
description: OpenAI plugin for Genkit Dart, provides seamless model integration, generative AI capabilities, and tooling support.
resolution: workspace
version: 0.0.1-dev.6
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.17
  json_schema_builder: ^0.1.3
  meta: ^1.17.0
  openai_dart: ^0.6.2
  schemantic: ^0.0.1-dev.18

dev_dependencies:
  build_runner: ^2.10.5
  build_test: ^3.5.5
  mockito: ^5.4.4
  test: ^1.29.0
