name: genkit_middleware
description: Middleware for Genkit Dart to inject skills.
version: 0.0.1-dev.1
resolution: workspace
environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.12
  logging: ^1.3.0
  mime: ^1.0.4
  path: ^1.9.0
  schemantic: ^0.0.1-dev.14

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
