name: _schema_generator
description: Tool for updating Dart clases in pkg:genkit
publish_to: none
environment:
  sdk: ^3.10.0
resolution: workspace

dependencies:
  build: ^4.0.4
  code_builder: ^4.10.0
  dart_style: ^3.1.4
  http: ^1.6.0
  json_annotation: ^4.9.0
  source_gen: ^4.1.2
