name: _schema_generator
description: Tool for updating Dart clases in pkg:genkit
publish_to: none
environment:
  sdk: ^3.10.0
resolution: workspace

dependencies:
  build: '>=3.0.0 <5.0.0'
  source_gen: '>=3.1.0 <5.0.0'
  http: ^1.2.1
  code_builder: ^4.10.0
  dart_style: ^3.0.0
  json_annotation: ^4.9.0
