name: mcp_server_sample
publish_to: none
description: Genkit MCP stdio server testapp
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.11
  genkit_mcp: ^0.0.1-dev.1
  schemantic: ^0.0.1-dev.13

dev_dependencies:
  build_runner: ^2.10.5
