name: mcp_server_sample
publish_to: none
description: Genkit MCP stdio server testapp
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.15
  genkit_mcp: ^0.0.1-dev.4
  schemantic: ^0.0.1-dev.16

dev_dependencies:
  build_runner: ^2.10.5
