name: genkit_google_genai
description: Google AI plugin for Genkit Dart.
resolution: workspace
version: 0.1.0-wip
repository: https://github.com/genkit-ai/genkit-dart

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  genkit: any
  google_cloud_ai_generativelanguage_v1beta: ^0.4.0
  google_cloud_protobuf: ^0.4.0
  json_annotation: ^4.9.0
  genkit_schema_builder: any

dev_dependencies:
  build_runner: ^2.8.0
  lints: ^6.0.0
  test: ^1.26.3
