name: genkit_google_genai
description: Google AI plugin for Genkit Dart.
resolution: workspace
version: 0.0.1-dev.6
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.6
  schemantic: ^0.0.1-dev.7
  google_cloud_ai_generativelanguage_v1beta: ^0.4.0
  google_cloud_protobuf: ^0.4.0
  json_annotation: ^4.9.0
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
