name: genkit_google_genai
description: Google AI plugin for Genkit Dart.
resolution: workspace
version: 0.0.1-dev.2
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  genkit: ^0.10.0-dev.2
  genkit_schema_builder: ^0.0.1-dev.1
  google_cloud_ai_generativelanguage_v1beta: ^0.4.0
  google_cloud_protobuf: ^0.4.0
  json_annotation: ^4.9.0
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.8.0
  lints: ^6.0.0
  test: ^1.26.3
