name: genkit_chrome
description: Chrome Built-in AI (Gemini Nano) plugin for Genkit Dart.
resolution: workspace
version: 0.0.1-dev.4
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.13
  json_annotation: ^4.9.0
  meta: ^1.17.0
  schemantic: ^0.0.1-dev.15
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
