name: openai_vertex_sample
publish_to: none
description: Genkit Dart Vertex OpenAI-compatible test application
resolution: workspace

executables:
  openai_vertex_sample: openai_vertex_sample

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.17
  genkit_openai: ^0.0.1-dev.6

dev_dependencies:
  test: ^1.29.0
