name: agentic_patterns
description: Agentic patterns samples for Genkit Dart
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  args: ^2.6.0
  genkit: any
  genkit_google_genai: any
  schemantic: any

dev_dependencies:
  build_runner: ^2.10.5
