name: Dart CI

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Dart Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap Workspace
        run: melos bootstrap

      # - name: Check Formatting
      #   run: dart format --output=none --set-exit-if-changed .

      - name: Run Code Generation
        run: melos exec --depends-on="build_runner" -o -- dart run build_runner build

      - name: Apply license headers
        run: dart run tools/apply_license.dart

      - name: Analyze Project Source
        run: melos run analyze

      - name: Run Tests
        run: melos run test

      - name: Verify clean git tree
        run: |
          git diff --exit-code
          if [ -n "$(git status --porcelain)" ]; then
            echo "Git directory is not clean. Working tree:"
            git status
            exit 1
          fi
