name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Dart Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sdk: ['3.10', dev]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap Workspace
        run: melos bootstrap

      # - name: Check Formatting
      #   if: matrix.sdk == '3.10'
      #   run: dart format --output=none --set-exit-if-changed .

      - name: Run Code Generation
        run: melos run build-gen

      - name: Apply license headers
        run: dart run tools/apply_license.dart

      - name: Analyze Project Source
        run: melos run analyze

      - name: Run Tests
        run: melos run test

      - name: Run Flutter Tests
        working-directory: packages/genkit_firebase_ai
        run: |
          flutter pub get
          dart run build_runner test
          dart run ../../tools/apply_license.dart
          flutter test

      - name: Verify clean git tree
        run: |
          git diff --exit-code
          if [ -n "$(git status --porcelain)" ]; then
            echo "Git directory is not clean. Working tree:"
            git status
            exit 1
          fi
