name: genkit
description: A type-safe Dart client library for calling Google Genkit flows with streaming support, authentication, and comprehensive error handling.
resolution: workspace
version: 0.10.0-dev.1
repository: https://github.com/genkit-ai/genkit-dart

environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.6.0
  json_schema_builder: ^0.1.3
  json_annotation: ^4.9.0
  meta: ^1.16.0
  opentelemetry: ^0.18.10
  path: ^1.9.0
  web_socket_channel: ^3.0.3
  genkit_schema_builder: any
  logging: ^1.3.0

dev_dependencies:
  build_runner: ^2.8.0
  lints: ^6.0.0
  async: ^2.11.0
  test: ^1.26.3
  mockito: ^5.5.1
  json_serializable: ^6.11.1
  code_builder: ^4.10.0
  dart_style: ^3.1.2
