name: basic_sample
publish_to: none
description: Genkit Dart basic testapp
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.10
  genkit_google_genai: ^0.0.1-dev.10
  genkit_shelf: ^0.0.1-dev.10
  http: ^1.6.0
  schemantic: ^0.0.1-dev.12
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
  test: ^1.29.0
