name: basic_sample
publish_to: none
description: Genkit Dart basic testapp
resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  genkit: ^0.10.0-dev.2
  genkit_google_genai: ^0.0.1-dev.2
  genkit_shelf: ^0.0.1-dev.2
  json_annotation: ^4.9.0
  genkit_schema_builder: any
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  build_runner: ^2.8.0
  lints: ^6.0.0
  test: ^1.26.3
  json_serializable: ^6.11.1
