name: basic_sample
publish_to: none
description: Genkit Dart basic testapp
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.10.0-dev.3
  genkit_google_genai: ^0.0.1-dev.3
  genkit_shelf: ^0.0.1-dev.3
  json_annotation: ^4.9.0
  schemantic: ^0.0.1-dev.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  build_runner: ^2.10.5
  lints: ^6.0.0
  test: ^1.29.0
  json_serializable: ^6.11.4
