name: genkit_mcp
description: MCP integration for Genkit Dart.
resolution: workspace
version: 0.0.1-dev.6
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: ^3.10.0

dependencies:
  crypto: ^3.0.6
  genkit: ^0.10.0-dev.17
  logging: ^1.3.0
  schemantic: ^0.0.1-dev.18

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
